services:
  - type: web
    name: teddy-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: MALLOC_ARENA_MAX
        value: 2
      - key: WEB_CONCURRENCY
        value: 1
    plan: starter # Specify the plan
    scaling:
      minInstances: 1
      maxInstances: 1 